package com.shcl.smarthealth.domain.model.remote.survey.answer.enumType

enum class DiseaseType {
    LUNG_CANCER, GASTRIC_CANCER, COLON_CANCER, LIVER_CANCER, THYROID_CANCER, BREAST_CANCER, COLON_CANCER_OR_RECTAL_CANCER, PANCREATIC_CANCER, ETC_CANCER,
    HIGH_BLOOD_PRESSURE, DIABETES, ANGINA_OR_MYOCARDIAL_INFARCTION, HYPERLIPIDEMIA, STROKE, TUBERCULOSIS_OF_LUNG, HEPATITIS, OSTEOPOROSIS, HYPERTHYROIDISM, HYPOTHYROIDISM, ASTHMA, ALLERGIC_RHINITIS, GASTRIC_ULCER_OR_DUODENAL_ULCER, REFLUX_ESOPHAGITIS, CHRONIC_KIDNEY_DISEASE, BENIGN_PROSTATIC_HYPERPLASIA, GLAUCOMA, ARTHRITIS, DEMENTIA, CHRONIC_HEPATITIS_OR_LIVER_CIRRHOSIS, ETC_DISEASE
}